deployment:
  apiVersion: apps/v1
  replicaCount: 1
  metadata:
    name: hello-python
  image:
    repository: hello-python
    tag: 1.0.0
  pullPolicy: Never

service:
  apiVersion: v1
  metadata:
    name: hello-python-service
  name: hello-python-service
  internalPort: 5000
  externalPort: 6000
  protocol: "TCP"
